// Philippines provinces, cities, and barangays
export const PHILIPPINES_LOCATIONS = [
  // Metro Manila
  'Metro Manila',
  // Manila
  'Manila - Binondo', 'Manila - Ermita', 'Manila - Intramuros', 'Manila - Malate', 'Manila - Paco', 'Manila - Pandacan', 'Manila - Port Area', 'Manila - Quiapo', 'Manila - Sampaloc', 'Manila - San Andres', 'Manila - San Miguel', 'Manila - San Nicolas', 'Manila - Santa Ana', 'Manila - Santa Cruz', 'Manila - Santa Mesa', 'Manila - Tondo',
  // Quezon City
  'Quezon City - Diliman', 'Quezon City - Cubao', 'Quezon City - Kamuning', 'Quezon City - New Manila', 'Quezon City - Project 2', 'Quezon City - Project 3', 'Quezon City - Project 4', 'Quezon City - Project 6', 'Quezon City - Project 7', 'Quezon City - Project 8', 'Quezon City - Barangay Bagong Silangan', 'Quezon City - Barangay Batasan Hills', 'Quezon City - Barangay Commonwealth', 'Quezon City - Barangay Payatas', 'Quezon City - Barangay Tandang Sora',
  // Makati
  'Makati - Ayala', 'Makati - Bel-Air', 'Makati - Dasmariñas Village', 'Makati - Forbes Park', 'Makati - Greenbelt', 'Makati - Legaspi Village', 'Makati - Pio del Pilar', 'Makati - Salcedo Village', 'Makati - San Antonio', 'Makati - San Lorenzo', 'Makati - Urdaneta Village', 'Makati - Barangay Bangkal', 'Makati - Barangay Cembo', 'Makati - Barangay Comembo', 'Makati - Barangay East Rembo', 'Makati - Barangay Guadalupe Nuevo', 'Makati - Barangay Guadalupe Viejo', 'Makati - Barangay Kasilawan', 'Makati - Barangay La Paz', 'Makati - Barangay Magallanes', 'Makati - Barangay Olympia', 'Makati - Barangay Palanan', 'Makati - Barangay Pembo', 'Makati - Barangay Pinagkaisahan', 'Makati - Barangay Pitogo', 'Makati - Barangay Poblacion', 'Makati - Barangay Post Proper Northside', 'Makati - Barangay Post Proper Southside', 'Makati - Barangay Rizal', 'Makati - Barangay San Isidro', 'Makati - Barangay Singkamas', 'Makati - Barangay South Cembo', 'Makati - Barangay Tejeros', 'Makati - Barangay Valenzuela', 'Makati - Barangay West Rembo',
  // Taguig
  'Taguig - Bonifacio Global City', 'Taguig - Barangay Bagumbayan', 'Taguig - Barangay Bambang', 'Taguig - Barangay Calzada', 'Taguig - Barangay Central Bicutan', 'Taguig - Barangay Central Signal Village', 'Taguig - Barangay Fort Bonifacio', 'Taguig - Barangay Hagonoy', 'Taguig - Barangay Ibayo-Tipas', 'Taguig - Barangay Katuparan', 'Taguig - Barangay Ligid-Tipas', 'Taguig - Barangay Lower Bicutan', 'Taguig - Barangay Maharlika Village', 'Taguig - Barangay Napindan', 'Taguig - Barangay New Lower Bicutan', 'Taguig - Barangay North Signal Village', 'Taguig - Barangay Palingon', 'Taguig - Barangay Pinagsama', 'Taguig - Barangay San Miguel', 'Taguig - Barangay Santa Ana', 'Taguig - Barangay South Signal Village', 'Taguig - Barangay Tanyag', 'Taguig - Barangay Upper Bicutan', 'Taguig - Barangay Ususan', 'Taguig - Barangay Wawa',
  // Pasig
  'Pasig - Barangay Bagong Ilog', 'Pasig - Barangay Bambang', 'Pasig - Barangay Buting', 'Pasig - Barangay Caniogan', 'Pasig - Barangay Dela Paz', 'Pasig - Barangay Kalawaan', 'Pasig - Barangay Kapasigan', 'Pasig - Barangay Kapitolyo', 'Pasig - Barangay Malinao', 'Pasig - Barangay Manggahan', 'Pasig - Barangay Maybunga', 'Pasig - Barangay Oranbo', 'Pasig - Barangay Palatiw', 'Pasig - Barangay Pinagbuhatan', 'Pasig - Barangay Pineda', 'Pasig - Barangay Rosario', 'Pasig - Barangay Sagad', 'Pasig - Barangay San Antonio', 'Pasig - Barangay San Joaquin', 'Pasig - Barangay San Jose', 'Pasig - Barangay San Miguel', 'Pasig - Barangay San Nicolas', 'Pasig - Barangay Santa Cruz', 'Pasig - Barangay Santa Lucia', 'Pasig - Barangay Santa Rosa', 'Pasig - Barangay Santo Tomas', 'Pasig - Barangay Sumilang', 'Pasig - Barangay Ugong',
  // Mandaluyong
  'Mandaluyong - Barangay Addition Hills', 'Mandaluyong - Barangay Bagong Silang', 'Mandaluyong - Barangay Barangka Drive', 'Mandaluyong - Barangay Barangka Ibaba', 'Mandaluyong - Barangay Barangka Ilaya', 'Mandaluyong - Barangay Barangka Itaas', 'Mandaluyong - Barangay Buayang Bato', 'Mandaluyong - Barangay Burol', 'Mandaluyong - Barangay Daang Bakal', 'Mandaluyong - Barangay Hagdang Bato Itaas', 'Mandaluyong - Barangay Hagdang Bato Libis', 'Mandaluyong - Barangay Harapin Ang Bukas', 'Mandaluyong - Barangay Highway Hills', 'Mandaluyong - Barangay Hulo', 'Mandaluyong - Barangay Mabini-J. Rizal', 'Mandaluyong - Barangay Malamig', 'Mandaluyong - Barangay Mauway', 'Mandaluyong - Barangay Namayan', 'Mandaluyong - Barangay New Zañiga', 'Mandaluyong - Barangay Old Zañiga', 'Mandaluyong - Barangay Pag-asa', 'Mandaluyong - Barangay Plainview', 'Mandaluyong - Barangay Pleasant Hills', 'Mandaluyong - Barangay Poblacion', 'Mandaluyong - Barangay San Jose', 'Mandaluyong - Barangay Vergara', 'Mandaluyong - Barangay Wack-Wack Greenhills',
  // Marikina
  'Marikina - Barangay Barangka', 'Marikina - Barangay Calumpang', 'Marikina - Barangay Concepcion Uno', 'Marikina - Barangay Concepcion Dos', 'Marikina - Barangay Fortune', 'Marikina - Barangay Industrial Valley Complex', 'Marikina - Barangay Jesus de la Peña', 'Marikina - Barangay Malanday', 'Marikina - Barangay Marikina Heights', 'Marikina - Barangay Nangka', 'Marikina - Barangay Parang', 'Marikina - Barangay San Roque', 'Marikina - Barangay Santa Elena', 'Marikina - Barangay Santo Niño', 'Marikina - Barangay Tañong', 'Marikina - Barangay Tumana',
  // Other Metro Manila Cities
  'Caloocan', 'Las Piñas', 'Malabon', 'Muntinlupa', 'Navotas', 'Parañaque', 'Pasay', 'Pateros', 'San Juan', 'Valenzuela',
  // Major Cities in Luzon
  'Baguio', 'Angeles City', 'Olongapo', 'Batangas City', 'Lucena', 'Antipolo', 'Cainta', 'Taytay', 'San Pedro', 'Biñan', 'Santa Rosa', 'Calamba', 'Los Baños', 'San Pablo', 'Tagaytay', 'Cavite City', 'Dasmariñas', 'Imus', 'Bacoor', 'General Trias', 'Trece Martires', 'Silang', 'Amadeo', 'Indang', 'Kawit', 'Magallanes', 'Maragondon', 'Mendez', 'Naic', 'Noveleta', 'Rosario', 'Tanza', 'Ternate',
  // Major Cities in Visayas
  // Cebu City with barangays
  'Cebu City - Barangay Adlaon', 'Cebu City - Barangay Agsungot', 'Cebu City - Barangay Apas', 'Cebu City - Barangay Babag', 'Cebu City - Barangay Bacayan', 'Cebu City - Barangay Banilad', 'Cebu City - Barangay Binaliw', 'Cebu City - Barangay Bonbon', 'Cebu City - Barangay Budlaan', 'Cebu City - Barangay Buhi', 'Cebu City - Barangay Bulacao', 'Cebu City - Barangay Buot-Taup', 'Cebu City - Barangay Busay', 'Cebu City - Barangay Calamba', 'Cebu City - Barangay Capitol Site', 'Cebu City - Barangay Carreta', 'Cebu City - Barangay Cogon Ramos', 'Cebu City - Barangay Day-as', 'Cebu City - Barangay Ermita', 'Cebu City - Barangay Guba', 'Cebu City - Barangay Hipodromo', 'Cebu City - Barangay Inayawan', 'Cebu City - Barangay Kalubihan', 'Cebu City - Barangay Kamagayan', 'Cebu City - Barangay Kamputhaw', 'Cebu City - Barangay Kasambagan', 'Cebu City - Barangay Kinasang-an', 'Cebu City - Barangay Labangon', 'Cebu City - Barangay Lahug', 'Cebu City - Barangay Lorega San Miguel', 'Cebu City - Barangay Lusaran', 'Cebu City - Barangay Luz', 'Cebu City - Barangay Mabini', 'Cebu City - Barangay Mabolo', 'Cebu City - Barangay Malubog', 'Cebu City - Barangay Mambaling', 'Cebu City - Barangay Pahina Central', 'Cebu City - Barangay Pahina San Nicolas', 'Cebu City - Barangay Pamutan', 'Cebu City - Barangay Parian', 'Cebu City - Barangay Pasil', 'Cebu City - Barangay Pit-os', 'Cebu City - Barangay Poblacion Pardo', 'Cebu City - Barangay Pulangbato', 'Cebu City - Barangay Pung-ol Sibugay', 'Cebu City - Barangay Punta Princesa', 'Cebu City - Barangay Quiot', 'Cebu City - Barangay Sambag I', 'Cebu City - Barangay Sambag II', 'Cebu City - Barangay San Antonio', 'Cebu City - Barangay San Jose', 'Cebu City - Barangay San Nicolas Proper', 'Cebu City - Barangay San Roque', 'Cebu City - Barangay Santa Cruz', 'Cebu City - Barangay Sapangdaku', 'Cebu City - Barangay Sawang Calero', 'Cebu City - Barangay Sinsin', 'Cebu City - Barangay Sirao', 'Cebu City - Barangay Suba', 'Cebu City - Barangay Sudlon I', 'Cebu City - Barangay Sudlon II', 'Cebu City - Barangay Tabunan', 'Cebu City - Barangay Tagbao', 'Cebu City - Barangay Talamban', 'Cebu City - Barangay Taptap', 'Cebu City - Barangay Tejero', 'Cebu City - Barangay Tinago', 'Cebu City - Barangay Tisa', 'Cebu City - Barangay Toong', 'Cebu City - Barangay Zapatera', 'Cebu City - Barangay Biasong',
  // Talisay City with barangays
  'Talisay City - Barangay Biasong', 'Talisay City - Barangay Bulacao', 'Talisay City - Barangay Candulawan', 'Talisay City - Barangay Camp IV', 'Talisay City - Barangay Dumlog', 'Talisay City - Barangay Jaclupan', 'Talisay City - Barangay Lagtang', 'Talisay City - Barangay Lawaan I', 'Talisay City - Barangay Lawaan II', 'Talisay City - Barangay Lawaan III', 'Talisay City - Barangay Linao', 'Talisay City - Barangay Maghaway', 'Talisay City - Barangay Manipis', 'Talisay City - Barangay Mohon', 'Talisay City - Barangay Poblacion', 'Talisay City - Barangay Pooc', 'Talisay City - Barangay San Isidro', 'Talisay City - Barangay San Roque', 'Talisay City - Barangay Tabunok', 'Talisay City - Barangay Tangke',
  // Mandaue City with barangays
  'Mandaue City - Barangay Alang-alang', 'Mandaue City - Barangay Bakilid', 'Mandaue City - Barangay Banilad', 'Mandaue City - Barangay Basak', 'Mandaue City - Barangay Cabancalan', 'Mandaue City - Barangay Cambaro', 'Mandaue City - Barangay Canduman', 'Mandaue City - Barangay Casili', 'Mandaue City - Barangay Casuntingan', 'Mandaue City - Barangay Centro', 'Mandaue City - Barangay Cubacub', 'Mandaue City - Barangay Guizo', 'Mandaue City - Barangay Ibabao-Estancia', 'Mandaue City - Barangay Jagobiao', 'Mandaue City - Barangay Labogon', 'Mandaue City - Barangay Looc', 'Mandaue City - Barangay Maguikay', 'Mandaue City - Barangay Mantuyong', 'Mandaue City - Barangay Opao', 'Mandaue City - Barangay Paknaan', 'Mandaue City - Barangay Pagsabungan', 'Mandaue City - Barangay Subangdaku', 'Mandaue City - Barangay Tabok', 'Mandaue City - Barangay Tawason', 'Mandaue City - Barangay Tingub', 'Mandaue City - Barangay Tipolo', 'Mandaue City - Barangay Umapad',
  // Lapu-Lapu City with barangays
  'Lapu-Lapu City - Barangay Agus', 'Lapu-Lapu City - Barangay Babag', 'Lapu-Lapu City - Barangay Bankal', 'Lapu-Lapu City - Barangay Baring', 'Lapu-Lapu City - Barangay Basak', 'Lapu-Lapu City - Barangay Buaya', 'Lapu-Lapu City - Barangay Calawisan', 'Lapu-Lapu City - Barangay Canjulao', 'Lapu-Lapu City - Barangay Caw-oy', 'Lapu-Lapu City - Barangay Cawhagan', 'Lapu-Lapu City - Barangay Caubian', 'Lapu-Lapu City - Barangay Gun-ob', 'Lapu-Lapu City - Barangay Ibo', 'Lapu-Lapu City - Barangay Looc', 'Lapu-Lapu City - Barangay Mactan', 'Lapu-Lapu City - Barangay Maribago', 'Lapu-Lapu City - Barangay Marigondon', 'Lapu-Lapu City - Barangay Pajac', 'Lapu-Lapu City - Barangay Pajo', 'Lapu-Lapu City - Barangay Poblacion', 'Lapu-Lapu City - Barangay Punta Engaño', 'Lapu-Lapu City - Barangay Pusok', 'Lapu-Lapu City - Barangay Sabang', 'Lapu-Lapu City - Barangay Santa Rosa', 'Lapu-Lapu City - Barangay Suba-basbas', 'Lapu-Lapu City - Barangay Talima', 'Lapu-Lapu City - Barangay Tingo', 'Lapu-Lapu City - Barangay Tungasan',
  // Consolacion with barangays
  'Consolacion - Barangay Cabangahan', 'Consolacion - Barangay Cansaga', 'Consolacion - Barangay Casili', 'Consolacion - Barangay Danglag', 'Consolacion - Barangay Garing', 'Consolacion - Barangay Jugan', 'Consolacion - Barangay Lamac', 'Consolacion - Barangay Lanipga', 'Consolacion - Barangay Nangka', 'Consolacion - Barangay Panas', 'Consolacion - Barangay Panoypoy', 'Consolacion - Barangay Pitogo', 'Consolacion - Barangay Poblacion East', 'Consolacion - Barangay Poblacion West', 'Consolacion - Barangay Polog', 'Consolacion - Barangay Pulpogan', 'Consolacion - Barangay Sacris', 'Consolacion - Barangay Tayud', 'Consolacion - Barangay Tilhaong', 'Consolacion - Barangay Tolotolo', 'Consolacion - Barangay Tugbongan',
  // Liloan with barangays
  'Liloan - Barangay Cabadiangan', 'Liloan - Barangay Calero', 'Liloan - Barangay Catarman', 'Liloan - Barangay Cotcot', 'Liloan - Barangay Jubay', 'Liloan - Barangay Lataban', 'Liloan - Barangay Mulao', 'Liloan - Barangay Poblacion', 'Liloan - Barangay San Roque', 'Liloan - Barangay San Vicente', 'Liloan - Barangay Santa Cruz', 'Liloan - Barangay Tabla', 'Liloan - Barangay Tayud', 'Liloan - Barangay Yati',
  // Compostela with barangays
  'Compostela - Barangay Bagalnga', 'Compostela - Barangay Basak', 'Compostela - Barangay Buluang', 'Compostela - Barangay Cabadiangan', 'Compostela - Barangay Cambayog', 'Compostela - Barangay Canamucan', 'Compostela - Barangay Cogon', 'Compostela - Barangay Dapdap', 'Compostela - Barangay Estaca', 'Compostela - Barangay Lupa', 'Compostela - Barangay Magay', 'Compostela - Barangay Mulao', 'Compostela - Barangay Panangban', 'Compostela - Barangay Poblacion', 'Compostela - Barangay Tag-ube', 'Compostela - Barangay Tamiao', 'Compostela - Barangay Tubigan',
  // Cordova with barangays
  'Cordova - Barangay Alegria', 'Cordova - Barangay Bangbang', 'Cordova - Barangay Buagsong', 'Cordova - Barangay Catarman', 'Cordova - Barangay Cogon', 'Cordova - Barangay Dapitan', 'Cordova - Barangay Day-as', 'Cordova - Barangay Gabi', 'Cordova - Barangay Gilutongan', 'Cordova - Barangay Ibabao', 'Cordova - Barangay Pilipog', 'Cordova - Barangay Poblacion', 'Cordova - Barangay San Miguel',
  // Minglanilla with barangays
  'Minglanilla - Barangay Calajo-an', 'Minglanilla - Barangay Camp 7', 'Minglanilla - Barangay Camp 8', 'Minglanilla - Barangay Cuanos', 'Minglanilla - Barangay Guindaruhan', 'Minglanilla - Barangay Linao', 'Minglanilla - Barangay Manduang', 'Minglanilla - Barangay Pakigne', 'Minglanilla - Barangay Poblacion Ward I', 'Minglanilla - Barangay Poblacion Ward II', 'Minglanilla - Barangay Poblacion Ward III', 'Minglanilla - Barangay Tubod', 'Minglanilla - Barangay Tulay', 'Minglanilla - Barangay Tungkil', 'Minglanilla - Barangay Tunghaan', 'Minglanilla - Barangay Vito',
  // Naga with barangays
  'Naga - Barangay Alpaco', 'Naga - Barangay Bairan', 'Naga - Barangay Balirong', 'Naga - Barangay Cabungahan', 'Naga - Barangay Cantao-an', 'Naga - Barangay Central Poblacion', 'Naga - Barangay Cogon', 'Naga - Barangay Colon', 'Naga - Barangay East Poblacion', 'Naga - Barangay Inoburan', 'Naga - Barangay Inayagan', 'Naga - Barangay Jaguimit', 'Naga - Barangay Lanas', 'Naga - Barangay Langtad', 'Naga - Barangay Lutac', 'Naga - Barangay Mainit', 'Naga - Barangay Mayana', 'Naga - Barangay Naalad', 'Naga - Barangay North Poblacion', 'Naga - Barangay Pangdan', 'Naga - Barangay Patag', 'Naga - Barangay South Poblacion', 'Naga - Barangay Tagjaguimit', 'Naga - Barangay Tangke', 'Naga - Barangay Tinaan', 'Naga - Barangay Tuyan', 'Naga - Barangay Uling', 'Naga - Barangay West Poblacion',
  // San Fernando with barangays
  'San Fernando - Barangay Balud', 'San Fernando - Barangay Balungag', 'San Fernando - Barangay Bugho', 'San Fernando - Barangay Cabatbatan', 'San Fernando - Barangay Greenhills', 'San Fernando - Barangay Ilaya', 'San Fernando - Barangay Linao', 'San Fernando - Barangay Panadtaran', 'San Fernando - Barangay Pitalo', 'San Fernando - Barangay Poblacion North', 'San Fernando - Barangay Poblacion South', 'San Fernando - Barangay Sangat', 'San Fernando - Barangay Tabionan', 'San Fernando - Barangay Tananas', 'San Fernando - Barangay Tubod',
  // Other Visayas cities
  'Toledo', 'Danao', 'San Francisco', 'Poro', 'Tudela', 'Pilar', 'Santa Fe', 'Bantayan', 'Madridejos', 'Daanbantayan', 'Medellin', 'San Remigio', 'Tabogon', 'Tabuelan', 'Tuburan', 'Asturias', 'Balamban', 'Barili', 'Bogo', 'Boljoon', 'Borbon', 'Carmen', 'Catmon', 'Dumanjug', 'Ginatilan', 'Malabuyoc', 'Oslob', 'Pinamungajan', 'Ronda', 'Samboan', 'Sibonga', 'Sogod',
  // Major Cities in Mindanao
  'Davao City', 'Cagayan de Oro', 'Zamboanga City', 'General Santos', 'Iligan', 'Butuan', 'Cotabato City', 'Marawi', 'Pagadian', 'Tacloban', 'Ormoc', 'Calbayog', 'Catbalogan', 'Maasin', 'Baybay', 'Borongan', 'Abuyog', 'Bato', 'Hilongos', 'Isabel', 'Javier', 'MacArthur', 'Mahaplag', 'Merida', 'Palo', 'San Isidro', 'San Miguel', 'Santa Fe', 'Tabango', 'Tabontabon', 'Tanauan', 'Tolosa', 'Tunga', 'Villaba'
];

// Helper function to get barangays for a specific city
export const getBarangaysForCity = (cityName: string) => {
  return PHILIPPINES_LOCATIONS.filter(location => 
    location.toLowerCase().includes(cityName.toLowerCase()) && 
    location.includes(' - ')
  );
};
